[15.0][ADD]account_budget_propagate_date: apply the budget dates to budget lines
sygel-technology/sy-account-budgeting pull request #2
Opened 2024-07-12 11:43 UTC by RogerSans

This module allows you to apply the budget dates to budget lines.
T-6345

@HaraldPanten
@ValentinVinagre

2024-07-13 15:23 UTC, HaraldPanten requested changes
It's not correct. Check a couple of things:

1- In the Contributors, my email is not correct.

2- The following case cannot be carried out:

- I have a budget in which the start date is 01/01/2025 and the end date is 12/31/2025.
- On the lines, the start and end dates are 01/01/2025 and 12/31/2025 respectively.
- Change the budget date range to 01/01/2026 (start) and 12/31/2026 (end).
- When clicking on applying dates on budget lines, an error appears.

See these screenshots.

![Captura de pantalla de 2024-07-13 17-09-41](https://github.com/user-attachments/assets/d5a9e6fe-15a5-4a39-925a-afafcf524d9f)

![Captura de pantalla de 2024-07-13 17-09-52](https://github.com/user-attachments/assets/ca3ee7c5-45bf-4bf7-accc-1dcdc2548f21)

2024-07-15 07:51 UTC, RogerSans commented
> It's not correct. Check a couple of things:
> 
> 1- In the Contributors, my email is not correct.
> 
> 2- The following case cannot be carried out:
> 
> * I have a budget in which the start date is 01/01/2025 and the end date is 12/31/2025.
> * On the lines, the start and end dates are 01/01/2025 and 12/31/2025 respectively.
> * Change the budget date range to 01/01/2026 (start) and 12/31/2026 (end).
> * When clicking on applying dates on budget lines, an error appears.
> 
> See these screenshots.
> 
> ![Captura de pantalla de 2024-07-13 17-09-41](https://private-user-images.githubusercontent.com/32449357/348480623-d5a9e6fe-15a5-4a39-925a-afafcf524d9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMzAwMTcsIm5iZiI6MTcyMTAyOTcxNywicGF0aCI6Ii8zMjQ0OTM1Ny8zNDg0ODA2MjMtZDVhOWU2ZmUtMTVhNS00YTM5LTkyNWEtYWZhZmNmNTI0ZDlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDA3NDgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkMTc1N2MzYjIwODg3OTU3ZDg5MTE2MDEwY2MxNjNmMTFiMmE3YzAzNmNlNGU1ZWMyNzg3M2ZiN2FjMzMxNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iq-kJ2b99DPhRL-kXg8d0BSDAEQb4o2_nb2tVjDsDTg)
> 
> ![Captura de pantalla de 2024-07-13 17-09-52](https://private-user-images.githubusercontent.com/32449357/348480640-ca3ee7c5-45bf-4bf7-accc-1dcdc2548f21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMzAwMTcsIm5iZiI6MTcyMTAyOTcxNywicGF0aCI6Ii8zMjQ0OTM1Ny8zNDg0ODA2NDAtY2EzZWU3YzUtNDViZi00YmY3LWFjY2MtMWRjZGMyNTQ4ZjIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDA3NDgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyZTQ2NzljMjljZjRlYjk1MTQ5MzFkODdmNzMzM2I3MmVlNWY2ODEzMjQ3MGQ2NjM0NWIwOTM0M2RmNWRhMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BgtNJciNQfzi43i_Iq5EOijyu6XCIME9-wDoIVciUfk)

Done.

2024-07-22 07:34 UTC, HaraldPanten requested changes

2024-07-22 07:34 UTC, HaraldPanten commented on account_budget_propagate_date/README.rst
> +This module allows you to change the default font size of the invoice reports.
```suggestion
This module allows you to change the default font size of the invoice reports.
```

This is not correct.

2024-07-22 07:45 UTC, RogerSans commented on account_budget_propagate_date/README.rst
> +This module allows you to change the default font size of the invoice reports.
Solved

2024-07-22 09:58 UTC, HaraldPanten approved these changes
Functional review.

@manuelregidor could you review? THX

2024-07-22 13:08 UTC, manuelregidor requested changes
Please, change the PR title (task code is missing)

2024-07-22 13:08 UTC, manuelregidor commented on account_budget_propagate_date/README.rst
> +Maintainer
The sections related to the sygel repository in which this modules is gonna be included are missing.

2024-07-22 13:08 UTC, manuelregidor commented on account_budget_propagate_date/models/crossovered_budget.py
> +from odoo import models
Copyright info is missing.

2024-07-22 13:27 UTC, RogerSans commented on account_budget_propagate_date/README.rst
> +Maintainer
Added

2024-07-22 13:27 UTC, RogerSans commented on account_budget_propagate_date/models/crossovered_budget.py
> +from odoo import models
Added

2024-07-22 13:33 UTC, manuelregidor approved these changes
Technical review. LGTM

2024-07-24 05:47 UTC, manuel-florido commented
@RogerSans 

Addons table not updated, fix it pls

2024-09-04 06:12 UTC, merged